{{- if .Values.storage.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "supabase.storage.fullname" . }}
  namespace: {{ include "supabase.namespace" . }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
spec:
  type: {{ .Values.storage.service.type }}
  ports:
    - port: {{ .Values.storage.service.port }}
      targetPort: 5000
      protocol: TCP
      name: http
  namespace: {{ include "supabase.namespace" . }}
  selector:
    {{- include "supabase.storage.selectorLabels" . | nindent 4 }}
{{- end }}