{{- if .Values.auth.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "supabase.auth.fullname" . }}
  namespace: {{ include "supabase.namespace" . }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
spec:
  type: {{ .Values.auth.service.type }}
  ports:
    - port: {{ .Values.auth.service.port }}
      targetPort: 9999
      protocol: TCP
      name: http
  namespace: {{ include "supabase.namespace" . }}
  selector:
    {{- include "supabase.auth.selectorLabels" . | nindent 4 }}
{{- end }}