{{- if .Values.supavisor.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "supabase.supavisor.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
spec:
  type: {{ .Values.supavisor.service.type }}
  ports:
    - port: {{ .Values.supavisor.service.port }}
      targetPort: postgres
      protocol: TCP
      name: postgres
    - port: {{ .Values.supavisor.proxyPort }}
      targetPort: proxy
      protocol: TCP
      name: proxy
    - port: 4000
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "supabase.supavisor.selectorLabels" . | nindent 4 }}
{{- end }}

