{{- if .Values.kong.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "supabase.kong.fullname" . }}
  namespace: {{ include "supabase.namespace" . }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
spec:
  type: {{ .Values.kong.service.type }}
  ports:
    - port: {{ .Values.kong.service.port }}
      targetPort: 8000
      protocol: TCP
      name: http
  namespace: {{ include "supabase.namespace" . }}
  selector:
    {{- include "supabase.kong.selectorLabels" . | nindent 4 }}
{{- end }}