{{- if .Values.minio.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "supabase.minio.fullname" . }}
  namespace: {{ include "supabase.namespace" . }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
spec:
  type: {{ .Values.minio.service.type }}
  ports:
    - port: {{ .Values.minio.service.port }}
      targetPort: 9000
      protocol: TCP
      name: http
  namespace: {{ include "supabase.namespace" . }}
  selector:
    {{- include "supabase.minio.selectorLabels" . | nindent 4 }}
{{- end }}