{{- if .Values.vector.enabled -}}
{{- if .Values.vector.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "supabase.vector.serviceAccountName" . }}
  namespace: {{ include "supabase.namespace" . }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
  {{- with .Values.vector.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "supabase.fullname" . }}-reader
  namespace: {{ include "supabase.namespace" . }}
rules:
  - apiGroups: [""]
    resources: ["nodes", "namespaces", "pods"]
    verbs: ["list", "watch"]
  - apiGroups: [""]
    resources: ["pods/log"]
    resourceNames:
      - {{ include "supabase.fullname" . }}-*
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "supabase.fullname" . }}-view
  namespace: {{ include "supabase.namespace" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "supabase.vector.serviceAccountName" . }}
  namespace: {{ include "supabase.namespace" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "supabase.fullname" . }}-reader
  namespace: {{ include "supabase.namespace" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}