{{- if .Values.analytics.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "supabase.analytics.fullname" . }}
  namespace: {{ include "supabase.namespace" . }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
spec:
  type: {{ .Values.analytics.service.type }}
  ports:
    - port: {{ .Values.analytics.service.port }}
      targetPort: 4000
      protocol: TCP
      name: http
  namespace: {{ include "supabase.namespace" . }}
  selector:
    {{- include "supabase.analytics.selectorLabels" . | nindent 4 }}
{{- end }}