secret:
  jwt:
    anonKey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyAgCiAgICAicm9sZSI6ICJhbm9uIiwKICAgICJpc3MiOiAic3VwYWJhc2UtZGVtbyIsCiAgICAiaWF0IjogMTY0MTc2OTIwMCwKICAgICJleHAiOiAxNzk5NTM1NjAwCn0.dc_X5iR_VP_qT0zsiyj_I_OZ2T9FtRU2BBNWN8Bu4GE
    serviceKey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyAgCiAgICAicm9sZSI6ICJzZXJ2aWNlX3JvbGUiLAogICAgImlzcyI6ICJzdXBhYmFzZS1kZW1vIiwKICAgICJpYXQiOiAxNjQxNzY5MjAwLAogICAgImV4cCI6IDE3OTk1MzU2MDAKfQ.DaYlNEoUrrEn2Ig7tqibS-PHK5vgusbcbo7X36XVt4Q
    secret: your-super-secret-jwt-token-with-at-least-32-characters-long
  smtp:
    username: your-mail@supabase.kube.rio.software
    password: example123456
  dashboard:
    username: supabase
    password: this_password_is_insecure_and_should_be_updated
  db:
    password: example123456
  pooler:
    vaultEncKey: your-encryption-key-32-chars-min
  realtime:
    dbEncKey: supabaserealtime
    secretKeyBase: UpNVntn3cDxHJpq99YMc1T1AQgQpc8kfYTuRgBiYa15BLrx8etQoXz3gZv1/u2oq
  s3:
    keyId: your-s3-key-id
    accessKey: your-s3-access-key
  analytics:
    privateApiKey: your-super-secret-and-long-private-logflare-key
    publicApiKey: your-super-secret-and-long-public-logflare-key
  meta:
    cryptoKey: your-encryption-key-32-chars-min

init_db:
  image:
    repository: postgres
    tag: "17.4-alpine"

db:
  enabled: true
  livenessProbe:
    exec:
      command:
        - pg_isready
        - -U
        - postgres
    initialDelaySeconds: 3
  persistence:
    enabled: false

studio:
  environment:
    DEFAULT_ORGANIZATION_NAME: "My Organization"
    DEFAULT_PROJECT_NAME: "My Project"
    SUPABASE_PUBLIC_URL: https://supabase.kube.rio.software/
    NEXT_PUBLIC_ENABLE_LOGS: "true"

auth:
  environment:
    API_EXTERNAL_URL: https://supabase.kube.rio.software
    GOTRUE_SITE_URL: https://supabase.kube.rio.software
    GOTRUE_EXTERNAL_EMAIL_ENABLED: "true"
    GOTRUE_MAILER_AUTOCONFIRM: "true"
    GOTRUE_SMTP_ADMIN_EMAIL: "your-mail@supabase.kube.rio.software"
    GOTRUE_SMTP_HOST: "smtp.supabase.kube.rio.software"
    GOTRUE_SMTP_PORT: "587"
    GOTRUE_SMTP_SENDER_NAME: "your-mail@supabase.kube.rio.software"

storage:
  persistence:
    enabled: false

imgproxy:
  environment:
    IMGPROXY_ENABLE_WEBP_DETECTION: "true"
  persistence:
    enabled: false

kong:
  environment:
    KONG_DECLARATIVE_CONFIG: /usr/local/kong/kong.yml
    KONG_LOG_LEVEL: info
  ingress:
    enabled: true
    className: traefik
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-dns01
    tls:
      - secretName: example-ingress-tls
        hosts:
          - supabase.kube.rio.software
    hosts:
      - host: supabase.kube.rio.software
        paths:
          - path: /
            pathType: Prefix

vector:
  # livenessProbe:
  #   httpGet:
  #     path: /health
  #     port: 9001
  #   initialDelaySeconds: 3
  ## Vector requires logs from the control plane to function.
  ## This is normally stored in /var/log/pods
  ## Modify these values according to your environment.
  volumeMounts:
    - name: pod-logs
      mountPath: /var/log/pods
  volumes:
    - name: pod-logs
      hostPath:
        path: /var/log/pods
